[postgres]
# OPTION 1: Use Connection Pooler (RECOMMENDED - try this first)
host = "aws-0-eu-west-3.pooler.supabase.com"
database = "postgres"
user = "postgres.ubmzhttmrvqcqtvzlmah"
password = "K*Jupn7keLS%yii"
port = "6543"  # CHANGED: Use pooler port 6543, not 5432
sslmode = "require"

# Connection settings
connect_timeout = "20"
application_name = "ai_product_creator_app"

# OPTION 2: If pooler doesn't work, try direct connection
# Uncomment these lines and comment out the pooler config above:
# host = "aws-0-eu-west-3.compute.amazonaws.com"  # Remove .pooler for direct
# port = "5432"  # Use 5432 for direct connection
